bpd dockerization
GreenBuildingRegistry/bpd-gui pull request #103
Opened 2023-09-26 20:06 UTC by fablet

2023-11-02 17:54 UTC, eocathcart commented
@fablet I'd like to hold off on the update to Angular until January at this point given competing priorities. So lets make sure this is set and deployable on AWS.

2023-11-03 16:59 UTC, fablet commented
> @fablet I'd like to hold off on the update to Angular until January at this point given competing priorities. So lets make sure this is set and deployable on AWS.

@eocathcart The sandbox for this is deployed to AWS at https://bpd-sandbox-cont-01.isu48ac4j57a2.us-west-2.cs.amazonlightsail.com

The current AWS sandbox does not contain the map automation.  Those two branches are running in parallel so I could get that map update out to BPD production but I have been waiting for someone to review that branch and for you to pass on the go ahead from Travis for the non-interactive version of the map.

Once I get that sorted, I can get these branches synched up so that the AWS sandbox can also include the map update, but you can do a quick review of the sandbox functionality as it stands so we can get BPD sandbox fully migrated over once I have @morehavoc approval for this pull request

2023-11-10 01:04 UTC, morehavoc requested changes

2023-11-10 01:04 UTC, morehavoc commented on docker/nginx.conf
> +#mail {
Is this commented out for a reason? I generally don't like to leave large commented-out blocks like this in files.

2023-11-13 18:12 UTC, fablet commented on README.md
> +with an existing mySQL database, you may need to run `./manage.py migrate --settings=config.local --fake-initial`.
Honestly, I haven't run it from a brand new database, probably ever.  Since migrating the database and users was part of the initial SOW I pulled that DB into my local environment, and have been working from it ever since.  I think you should be able to spin it up from a brand new, empty database, but I can't be certain at this time.

2023-11-13 18:19 UTC, fablet commented on docker/nginx.conf
> +#mail {
I would agree about large commented-out blocks in code, but this is a minor modification of a default conf file.  When NGINX installs, it drops in this nginx.conf file, with most of the settings commented out.  It's usage is to edit, comment, or uncomment as needed/desired. 
Years ago, when Paul set up the devops cycle, we edited the default conf file slightly; I think to alter the SSL protocols.  I have been dropping this into every NGINX server deployment ever since.  But since it is just that minor alteration of the default conf, I prefer to leave it intact as it was designed to be by NGINX.

2023-11-13 18:26 UTC, fablet commented on README.md
> +as an attachment on `AWS - BPD Production`.
I added a note about this in the header section of the README

2023-11-14 18:02 UTC, morehavoc commented on README.md
> +with an existing mySQL database, you may need to run `./manage.py migrate --settings=config.local --fake-initial`.
Ahh, that makes sense. Would you just add a note here mentioning that someone might need to get the real database in order to run the app please?

2023-11-14 18:21 UTC, fablet commented on README.md
> +with an existing mySQL database, you may need to run `./manage.py migrate --settings=config.local --fake-initial`.
Done

2023-11-14 18:38 UTC, morehavoc approved these changes

2023-11-14 18:56 UTC, merged